from enum import Enum

class Shape(Enum):
    POINT = 0
    LINE = 1
    TRIANGLE = 2
    EQUILATERAL_TRIANGLE = 3
    ISOSCELES_TRIANGLE = 4
    SQUARE = 5
    RECTANGLE = 6
    RHOMBUS = 7
    PARALLELOGRAM = 8
    TRAPEZIUM = 9
    QUADRILLATERAL = 10
    PENTAGON = 11
    HEXAGON = 12
    HEPTAGON = 13
    OCTAGON = 14
    CIRCLE = 15
    ELIPSE = 16
    POLYGON = 17
    KITE = 18
    INVALID = 19


